apiVersion: v1
data:
  BOUCHON: "false"
  CMDBAPI: itsm-reporter.apps.itz-u0m8pt.infra01-lb.fra02.techzone.ibm.com
  DEBUG: "true"
  INSECURE: "true"
  ITSMAPI: itsm-reporter.apps.itz-u0m8pt.infra01-lb.fra02.techzone.ibm.com
  REPORTERAPI: ibm-license-service-reporter-reporter.apps.itz-u0m8pt.infra01-lb.fra02.techzone.ibm.com
kind: ConfigMap
metadata:
  name: config-endpoints-reporter
  namespace: NAMESPACE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsm-cronjob
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: SC_BLOCK
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: itsm-cronjob
  name: itsm-cronjob
  namespace: NAMESPACE
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: itsm-cronjob
            label1: label1
            label2: label2
        spec:
          containers:
          - env:
            - name: DEBUG
              valueFrom:
               configMapKeyRef:
                 name: config-endpoints-reporter
                 key: DEBUG
            - name: BOUCHON
              valueFrom:
               configMapKeyRef:
                 name: config-endpoints-reporter
                 key: BOUCHON
            - name: INSECURE
              valueFrom:
               configMapKeyRef:
                 name: config-endpoints-reporter
                 key: INSECURE
            - name: REPORTERAPI
              valueFrom:
               configMapKeyRef:
                 name: config-endpoints-reporter
                 key: REPORTERAPI
            - name: CMDBAPI
              valueFrom:
               configMapKeyRef:
                 name: config-endpoints-reporter
                 key: CMDBAPI
            - name: ITSMAPI
              valueFrom:
               configMapKeyRef:
                 name: config-endpoints-reporter
                 key: ITSMAPI
            command:
            - bash
            - -xv
            - /home/ubuntu/exec.sh
            image: IMAGE_REFERENCE
            imagePullPolicy: Always
            name: itsm
            resources:
              limits:
                cpu: 500m
                ephemeral-storage: 5Gi
                memory: 256Mi
              requests:
                cpu: 200m
                ephemeral-storage: 5Gi
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /data
              name: data
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: itsm-cronjob
          - name: lsrtoken
            secret:
              defaultMode: 420
              secretName: ibm-license-service-reporter-token
          serviceAccount: itsm
          serviceAccountName: itsm
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  suspend: false
